
namespace MotionCapture.Mediapipe
{
    public enum Bones 
    {
        nose = 0,
        left_inner_eye = 1,
        left_eye = 2,
        left_outer_eye = 3,
        right_inner_eye = 4,
        right_eye = 5,
        right_outer_eye = 6,
        left_ear = 7,
        right_ear = 8,
        left_mouth = 9,
        right_mouth = 10,
        left_shoulder = 11,
        right_shoulder = 12,
        left_elbow = 13,
        right_elbow = 14,
        left_wrist = 15,
        right_wrist = 16,
        left_outer_hand = 17,
        right_outer_hand = 18,
        left_hand_tip = 19,
        right_hand_tip = 20,
        left_inner_hand = 21,
        right_inner_hand = 22,
        left_hip = 23,
        right_hip = 24,
        left_knee = 25,
        right_knee = 26,
        left_ankle = 27,
        right_ankle = 28,
        left_heel = 29,
        right_heel = 30,
        left_toe = 31,
        right_toe = 32,
    }
}
