using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MotionCapture.RTMPose
{
    public enum Bone 
    {
        nose = 0,
        left_inner_eye = 65,
        left_eye = 1,
        left_outer_eye = 68,
        right_inner_eye = 62,
        right_eye = 2,
        right_outer_eye = 59,
        left_ear = 3,
        right_ear = 4,
        left_mouth = 77,
        right_mouth = 71,
        left_shoulder = 5,
        right_shoulder = 6,
        left_elbow = 7,
        right_elbow = 8,
        left_wrist = 9,
        right_wrist = 10,
        left_hip = 11,
        right_hip = 12,
        left_knee = 13,
        right_knee = 14,
        left_ankle = 15,
        right_ankle = 16,
        left_heel = 19,
        right_heel = 22,
        left_toe = 17,
        right_toe = 20,
        left_thumb_1 = 92,
        left_thumb_2 = 93,
        left_thumb_3 = 94,
        left_thumb_distal = 95,
        left_index_1 = 96,
        left_index_2 = 97,
        left_index_3 = 98,
        left_index_distal = 99,
        left_middle_1 = 100,
        left_middle_2 = 101,
        left_middle_3 = 102,
        left_middle_distal = 103,
        left_ring_1 = 104,
        left_ring_2 = 105,
        left_ring_3 = 106,
        left_ring_distal = 107,
        left_little_1 = 108,
        left_little_2 = 109,
        left_little_3 = 110,
        left_little_distal = 111,
        right_thumb_1 = 113,
        right_thumb_2 = 114,
        right_thumb_3 = 115,
        right_thumb_distal = 116,
        right_index_1 = 117,
        right_index_2 = 118,
        right_index_3 = 119,
        right_index_distal = 120,
        right_middle_1 = 121,
        right_middle_2 = 122,
        right_middle_3 = 123,
        right_middle_distal = 124,
        right_ring_1 = 125,
        right_ring_2 = 126,
        right_ring_3 = 127,
        right_ring_distal = 128,
        right_little_1 = 129,
        right_little_2 = 130,
        right_little_3 = 131,
        right_little_distal = 132
    }
}
